
export default {
  GITHUB_SEARCH_USER:           'github/SEARCH_USER',
  GITHUB_SEARCH_USER_SUCCEEDED: 'github/SEARCH_USER_SUCCEEDED',
  GITHUB_SEARCH_USER_FAILED:    'github/SEARCH_USER_FAILED',
  GITHUB_GET_USER:              'github/GET_USER',
  GITHUB_GET_USER_SUCCEEDED:    'github/GET_USER_SUCCEEDED',
  GITHUB_GET_USER_FAILED:       'github/GET_USER_FAILED',
}
